name: Upload

on:
  push:
    branches: [master]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build
        run: rake

      - name: Upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          filename="$(yq -r '.project_name' .sscharter.yml).ssc"
          build_dir="$(yq -r '.build_dir' .sscharter.yml)"
          aws s3 cp "$build_dir/$filename" "s3://${{ secrets.S3_BUCKET_NAME }}/chart/$filename" \
            --endpoint-url "${{ secrets.S3_ENDPOINT }}" \
            --checksum-algorithm CRC32 # The default is CRC64NVME, which is not supported by my S3 storage
